### ISSUE TITLE
Recursive mode

### ISSUE THREAD

**Issue by justanotherdot** [justanotherdot/stickybeak#3]
Provide functionality for recursively watching a directory as a flag specified in the config, e.g. 

```yaml
triggers:
  - name: "test"
    dirs: "."
    cmd: echo
    args: 'hello world!'
    recursive: true
```

Should watch all subdirectories for _every_ directory listed in `dirs`
